// This file is auto generated by `nuxt prepare`
// Please do not manually modify this file.

/// <reference types="@nuxtjs/tailwindcss" />
/// <reference types="@nuxtjs/style-resources" />
/// <reference types="@nuxtjs/svg" />
/// <reference types="@nuxtjs/eslint-module" />
/// <reference types="@nuxt/bridge-edge" />
/// <reference types="@nuxtjs/sentry" />
/// <reference types="@nuxtjs/sitemap" />
/// <reference types="nuxt-ssr-cache" />
/// <reference types="@nuxtjs/i18n" />
/// <reference types="@nuxt/components" />
/// <reference types="@nuxt/telemetry" />
/// <reference path=".nuxt/nitro.d.ts" />
/// <reference types="unplugin-vue2-script-setup/types" />
/// <reference path=".nuxt/auto-imports.d.ts" />
export {}
