name: openverse-frontend/setup-node-env
description: Setup the Node.js environment including `pnpm` and dependencies

inputs:
  install:
    default: true
    description: Whether to install dependencies.
  downloadLocales:
    required: false
    default: "false"
    description: Whether to download locales artifact.

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2.2.2

    - name: Cache pnpm modules
      uses: actions/cache@v3
      with:
        path: ~/.local/share/pnpm/store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: actions/setup-node@v3.3.0
      with:
        node-version: 16
        cache: pnpm
        cache-dependency-path: |
          pnpm-lock.yaml
          .npmrc

    - name: Install
      if: inputs.install
      shell: bash
      run: "pnpm install"

    - uses: actions/download-artifact@v3
      if: inputs.downloadLocales == 'true'
      with:
        name: locales
        path: src/locales
