#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Generate a new openverse.pot file if en.json has changes
POTFILE=src/locales/po-files/openverse.pot
pnpm i18n:generate-pot
CHANGED=$(git diff --staged --name-only HEAD)
if [[ "$CHANGED" == *"$POTFILE"* ]]; then
  git add $POTFILE
fi

# Lint staged files
pnpx lint-staged && pnpm types
