# this build is triggered when a new pre-release has been created
# it creates a new docker build image based on the tag associated

name: build

on:
  release:
    types:
      - 'prereleased'
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      # download the source code into the runner
      - name: checkout
        uses: actions/checkout@v2

      # gather metadata from git & github actions to reference in docker
      - name: git & github metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/openverse/frontend

      # setup docker buildx
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      # login in docker repository
      - name: docker login
        uses: aws-actions/amazon-ecr-login@v1

      # build a docker image
      - name: build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true


