name: openverse-frontend-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - audio

jobs:
  ci:
    name: Run CI tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.0
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Run lint
        run: pnpm lint

      - name: Run formatting test
        run: pnpm format:test

      - name: Run tests
        run: pnpm i18n:get-translations && pnpm test:unit

      - name: Run Storybook smoke-test
        run: pnpm storybook -- --ci --smoke-test
