name: CI

on:
  push:
    branches: -main
  pull_request:

jobs:
  types:
    name: Check types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Check types
        run: pnpm types

  lint:
    name: Lint files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: ESLint
        run: pnpm lint

      - name: Prettier
        run: pnpm format:test

  i18n:
    name: Check translation files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Check extracted strings
        run: pnpm vue-i18n-check

      - name: Check POT files are updated
        shell: bash
        run: pnpm i18n:generate-pot

  unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Run unit tests
        run: pnpm ci:unit-test

  e2e:
    name: E2E tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Run E2E
        run: PW_USER=root ./bin/playwright.sh e2e

  storybook:
    name: Check Storybook build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Run Storybook smoke-test
        run: pnpm storybook -- --ci --smoke-test

  build:
    name: Check Nuxt build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Run build
        run: pnpm build
