name: Update frontend task definition (redeploy)

on:
  push:
    branches:
      - main
  pull_request:

  release:
    types:
      - "released"
  workflow_dispatch:
    inputs:
      tag:
        description: Tag of the ghcr.io/wordpress/openverse-frontend image to use.
        required: true

jobs:
  update-task-definition-and-deploy:
    if: github.head_ref == 'fix/task-def-redeploy'
    name: Update task definition and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/frontend-deploy
        with:
          tag: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.sha) || (github.event_name == 'push' && 'main') || github.event.release.tag_name || 'main' }} # remove final || 'main' after testing
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
