name: Storybook GitHub Pages

# Temporarily commented out for testing
on:
  push:
    branches:
      - main
      - add/tailwind-config-viewer

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'WordPress/openverse-frontend' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Fetch translation files
        run: pnpm i18n

      - name: Build Storybook
        run: pnpm storybook:build

      - name: Build Tailwind Config Viewer
        run: pnpm tcv:build

      # This makes the TCV available at the `/tailwind` directory in the gh-pages
      - name: Merge TCV and Storybook builds
        run: mv .tcv-export ./storybook-static/tailwind

      - name: Deploy
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501 # v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          force_orphan: true
