name: GitHub Container Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push-to-ghcr:
    name: Build and push image for commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        with:
          install: true

      - uses: docker/login-action@v1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/wordpress/openverse-frontend
          tags: |
            type=sha
            type=ref,event=tag

      - name: Get pnpm-version
        id: pnpm-version
        run: |
          echo "::set-output name=val::$(cat .pnpm-version)"

      - uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true
          build-args: |
            PNPM_VERSION=${{ steps.pnpm-version.outputs.val }}
