name: GitHub Container Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push-to-ghcr:
    name: Build and push image for commit
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-buildx-action@v1
        with:
          install: true

      - uses: docker/login-action@v1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        with:
          images: wordpress/openverse-frontend
          tags: |
            type=sha
            type=ref,event=tag

      - uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.metadata_staging.outputs.tags }}
          labels: ${{ steps.metadata_staging.outputs.labels }}
          push: true
