name: GitHub Container Registry & Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  push-to-ghcr:
    name: Build and push image for commit
    runs-on: ubuntu-latest
    # prevent running on fork PRs
    if: github.event_name == 'push' || github.event_name == 'release' || github.event.pull_request.head.repo.owner.login == 'WordPress'

    steps:
      - name: Checkout branch or push to main
        uses: actions/checkout@v3
        if: github.event_name != 'release'

      - name: Checkout release
        uses: actions/checkout@v3
        if: github.event_name == 'release'
        with:
          ref: ${{ github.event.release.tag_name }}

      - uses: docker/setup-buildx-action@v2
        with:
          install: true

      - uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ghcr.io/wordpress/openverse-frontend
          tags: |
            type=sha
            type=ref,event=tag
            ${{ github.event_name == 'push' && 'type=raw,value=main' || '' }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true

  deploy-staging:
    name: Deploy staging frontend
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: push-to-ghcr

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/staging-frontend-deploy
        with:
          tag: "main"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy-production:
    name: Deploy production frontend
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: push-to-ghcr

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: ./.github/actions/production-frontend-deploy
        with:
          tag: ${{ github.event.release.tag_name }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
