name: GitHub Container Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push-to-ghcr:
    name: Build and push image for commit
    runs-on: ubuntu-latest
    if: github.repository == 'WordPress/openverse-frontend'

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v2
        with:
          install: true

      - uses: docker/login-action@v1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/wordpress/openverse-frontend
          tags: |
            type=sha
            type=ref,event=tag
            ${{ github.event_name == 'push' && 'type=raw,value=main' || '' }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true
