# this workflow will try to lint and build a node.js application
#
# this is useful for stages that you require making sure everything is working
# properly before creating a container image to be pushed on the cloud
#
name: openverse/validate

on:
  pull_request:
#  push:
#    branches:
#      - 'main'
#      - 'ci/*' # branches that follows the pattern ci/* can access this workflow too

jobs:
  pre_build:
    name: pre_build
    runs-on: ubuntu-latest

    steps:
      # download the source code into the runner
      - name: checkout
        uses: actions/checkout@v2

      # setup node.js environment and npm
      - name: setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.0
          # Set this to false because we want to be able to skip installation if there is a cache hit in the next step
          run_install: false

      # install dependencies only if the cache is not present
      - name: install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      # run lint and syntax
      - name: lint & syntax check
        run: pnpm lint

      # run type checker
      - name: typescript
        run: pnpm types
