# this build is triggered when a new pull request has been merged
# into the main branch

name: push_staging

on:
  push:
    branches:
      - main

jobs:
  push:
    name: push
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://search-staging.openverse.engineering

    steps:
      # download the source code into the runner
      - name: checkout
        uses: actions/checkout@v2

      # build a new docker image and push it into the repository
      - name: docker build
        uses: ./.github/workflows/build.yaml@v1
        with:
          is_production: false
