name: Redeploy staging frontend

on:
  push:
    branches:
      - main

jobs:
  update-task-definition-and-deploy:
    name: Update task definition and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/staging-frontend-deploy
        with:
          tag: "main"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
