name: static-analysis

on:
  push:
    branches:
      -main
  pull_request:

jobs:
  types:
    name: Check types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Check types
        run: pnpm types

  lint:
    name: Lint files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: ESLint
        run: pnpm lint

      - name: Prettier
        run: pnpm format:test

  i18n:
    name: Check translation files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Check extracted strings
        run: pnpm vue-i18n-check

      - name: Check POT files are updated
        shell: bash
        run: |
          pnpm i18n:generate-pot
          exit $(git status -s -uno | wc -l)
